//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Requerimientos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Estado_novedades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estado_novedades()
        {
            this.Novedades = new HashSet<Novedades>();
        }
    
        public int idestadonovedad { get; set; }

        [Required(ErrorMessage = "La Descripcion es requerida")]     
        public string Descripcion { get; set; }
        public Nullable<int> idusuario { get; set; }
        [Required(ErrorMessage = "El color es requerido")]
        public string color { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Novedades> Novedades { get; set; }
    }
}
