//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Requerimientos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mensajes()
        {
            this.Archivos = new HashSet<Archivos>();
            this.Novedades = new HashSet<Novedades>();
            this.HistorialDelega = new HashSet<HistorialDelega>();
        }

        public int Id { get; set; }
        public int User_Id { get; set; }
        public string Remitente { get; set; }
        [Required(ErrorMessage = "El Asunto es requerido")]
        [MaxLength(100, ErrorMessage = "El Asunto es demasiado largo")]
        public string Asunto { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Status { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Idusuariodestino { get; set; }
        public string Maildestino { get; set; }
        public string Destinatario { get; set; }
        public string Email { get; set; }
        public Nullable<int> Idpadre { get; set; }
        [Required(ErrorMessage = "El proyecto es requerido")]
        public Nullable<int> Idproyecto { get; set; }
        public Nullable<int> Idusuariodelega { get; set; }
        public string Usuariodelega { get; set; }
        public Nullable<int> Idestado { get; set; }
        public Nullable<int> IdCarpeta { get; set; }
        public virtual bool Enviamail { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Archivos> Archivos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Novedades> Novedades { get; set; }
        public virtual Proyectos Proyectos { get; set; }
        public virtual Estado_requerimiento Estado_requerimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialDelega> HistorialDelega { get; set; }
        public virtual Carpetas Carpetas { get; set; }
    }
}
