//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Requerimientos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Novedades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Novedades()
        {
            this.Archivos = new HashSet<Archivos>();
        }
    
        public int Idnovedad { get; set; }
        [Required(ErrorMessage = "La Descripcion es requerida")]
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Idmensaje { get; set; }
        public string Estado { get; set; }
        public string Usuario { get; set; }
        [Required(ErrorMessage = "El titulo es requerida")]
       [MaxLength(100, ErrorMessage = "El titulo es demasiado largo")]
        public string Titulo { get; set; }
        public Nullable<int> Idproyecto { get; set; }
        public Nullable<int> Idestadonovedad { get; set; }
        public Nullable<int> User_Id { get; set; }
        public bool Privado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Archivos> Archivos { get; set; }
        public virtual Mensajes Mensajes { get; set; }
        public virtual Proyectos Proyectos { get; set; }
        public virtual Estado_novedades Estado_novedades { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
